#!/bin/sh /etc/rc.common
# Starts and stops MQTT-SN GW
# /etc/init.d/mqtt-sn

START=90
STOP=10

# PID and binary file for start-stop-daemon
PIDFILE=/var/run/mqtt-sn.pid
DAEMON=/usr/bin/MQTT-SNGateway

# test if binary exists and execute permission is granted
test -x ${DAEMON} || exit 0

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

start() {
    echo "Starting MQTT-SN Gateway"
    if start-stop-daemon -S -q -b -m -p ${PIDFILE} -x ${DAEMON} -- -f /etc/mqttsn-gw/gateway.conf ; then
        exit 0
    else
        exit 1
    fi
}

stop() {
    echo "Stopping MQTT-SNGateway"
    if start-stop-daemon -K -q -s SIGKILL -p ${PIDFILE}; then
        rm -f ${PIDFILE}
        exit 0
    else
        exit 1
    fi
}

restart() {
    echo "Restarting MQTT-SNGateway" "MQTT-SNGateway"
    if start-stop-daemon -K -q -s SIGKILL -p ${PIDFILE}; then
        rm -f ${PIDFILE}
    fi
    if start-stop-daemon -S -q -b -m -p ${PIDFILE} -x ${DAEMON} -- -f /etc/mqttsn-gw/gateway.conf ; then
        exit 0
    else
        exit 1
    fi
}
